excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://inside.shiftconnects.com
title: Inside SHIFT
tagline: Peek under the hood
description: Be on your way within five minutes.
paginate: 5